# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NPM package publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git config --global user.email "ari@paperclicks.net"
    - run: git config --global user.name "Ari Bot"
    - run: npm version minor -m "[skip ci] %s"
    - run: npm i 
    - run: npm run build-bundle 
    # COMMIT VERSION
  # You may pin to the exact commit or the version.
  # uses: zakiego/just-git-push@bd8adc135244d713200dd36b27ada4144989dcbd
    - name: Just Git Push
      uses: zakiego/just-git-push@v0.1.0
        with:
          USERNAME: "Ari Bot"
          EMAIL: "ari@paperclicks.net"
          COMMIT_MESSAGE: "This is an automated commit by GitHub Actions. update version"
          BRANCH: ${{ github.ref_name }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    # Publish package
    - name: NPM Publish
    # You may pin to the exact commit or the version.
    # uses: JS-DevTools/npm-publish@4b07b26a2f6e0a51846e1870223e545bae91c552 
      uses: JS-DevTools/npm-publish@v3.0.1
      with:
        # The NPM access token to use when publishing
        token: ${{ secrets.NPM_TOKEN }}
